file:
  fileUrl: http://localhost:8080/files/
  fileMap: /files/**
  filePath: D://upload/
spring:
  http:
    multipart:
      max-file-size: -1
  datasource:
    url: jdbc:mysql://localhost:3306/studyvue
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
#    driver-class-name: